// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gsp "github.com/fluxynet/go-scratch-prod"
	mock "github.com/stretchr/testify/mock"
)

// TaskRepo is an autogenerated mock type for the TaskRepo type
type TaskRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, task
func (_m *TaskRepo) Create(ctx context.Context, task gsp.Task) (*gsp.Task, error) {
	ret := _m.Called(ctx, task)

	var r0 *gsp.Task
	if rf, ok := ret.Get(0).(func(context.Context, gsp.Task) *gsp.Task); ok {
		r0 = rf(ctx, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gsp.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gsp.Task) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, id
func (_m *TaskRepo) Get(ctx context.Context, id string) (*gsp.Task, error) {
	ret := _m.Called(ctx, id)

	var r0 *gsp.Task
	if rf, ok := ret.Get(0).(func(context.Context, string) *gsp.Task); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gsp.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *TaskRepo) List(ctx context.Context) ([]gsp.Task, error) {
	ret := _m.Called(ctx)

	var r0 []gsp.Task
	if rf, ok := ret.Get(0).(func(context.Context) []gsp.Task); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gsp.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, task
func (_m *TaskRepo) Update(ctx context.Context, task gsp.Task) error {
	ret := _m.Called(ctx, task)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, gsp.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTaskRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewTaskRepo creates a new instance of TaskRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTaskRepo(t mockConstructorTestingTNewTaskRepo) *TaskRepo {
	mock := &TaskRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
